### ISSUE TITLE
[migration]

### ISSUE THREAD

**Issue by RimiChen** [SoftwareEngineeringToolDemos/FSE-2014-BumbleBee#2]
This repository seemed not to be forked or migrated from another repo.

**Comment by sujithktkm** [comment]
There is no Gihub repository for BumbleBee, thus it was not forked or migrated from different repo. Can I go ahead and close this? Also, I was not given source code/license to share source code.

**Comment by RimiChen** [comment]
I added information about repository history to README.

**Comment by sujithktkm** [comment]
@RimiChen  Can you send a PR first and close the issue once I merge the PR ? It helps in tracking the issue in a much better way. [Same thing for other issues, but I am not reopening all of them]

**Comment by RimiChen** [comment]
OK, I redo all the change with pull request. Thanks!
