### ISSUE TITLE
[Other] Cannot check [contradiction]

### ISSUE THREAD

**Issue by RimiChen** [SoftwareEngineeringToolDemos/FSE-2014-BumbleBee#4]
Didn't know the license information (or permission), so I didn't check [contradiction].

**Comment by sujithktkm** [comment]
Is this speaking about license information about source code @RimiChen ?

**Comment by sujithktkm** [comment]
Information on 'not to' distribute source code of tool was sent in an email from author. Also, the tool is unworkable, so nothing that could be done from my side.
