### ISSUE TITLE
[To repo owner] Please leave some issues to our team to match the assignment requirement

### ISSUE THREAD

**Issue by RimiChen** [SoftwareEngineeringToolDemos/FSE-2014-BumbleBee#5]
Hi~
Sujith Katakam.

I saw that you updated the README.md (solved all the problems and closed all issues) immediately, according to the issues. That was really good.

And, honestly, when reviewing your repo (I checked all criteria, bullet by bullet according to assignment requirement on moodle), your README.md almost match all the requirements,  except those unsolvable (like source code for unworkable tool). 

But, since the professor  said that we (review team) are required fix  3 issues (it seems that you have solved all of them), I will open 3 other issues for our team to solve and to match the requirement. Could you please accept our pull requests then? I probably will update the license information, thanks part, something like that.

Thank you.

**Comment by sujithktkm** [comment]
@RimiChen Sorry about that. There is an option called 'Assignee' while creating an issue. Use that to assign an issue either to me or yourself. This will makes things clear on which ones I should be working on.

**Comment by sujithktkm** [comment]
Hi,

I see that you have assigned three issues to yourself in this repo. Can I close this issue?
